package org.sundbybergheat.baseballstreaming.models.wbsc.play;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

public record Player(
    @JsonProperty("name") Optional<String> fullName,
    @JsonProperty("firstname") Optional<String> firstName,
    @JsonProperty("lastname") Optional<String> lastName,
    @JsonProperty("playerid") Optional<String> playerId,
    @JsonProperty("teamid") Optional<String> teamId,
    @JsonProperty("teamcode") Optional<String> teamCode,
    @JsonProperty("image") Optional<String> imageUrl,
    @JsonProperty("inplay") Optional<String> inPlay,
    @JsonProperty("reentry") Optional<String> reEntry,
    @JsonProperty("POS") Optional<String> position,
    @JsonProperty("PA") Optional<String> plateAppearances,
    @JsonProperty("AB") Optional<String> atBats,
    @JsonProperty("R") Optional<String> runs,
    @JsonProperty("H") Optional<String> hits,
    @JsonProperty("RBI") Optional<String> runsbattedIn,
    @JsonProperty("BB") Optional<String> walks,
    @JsonProperty("SO") Optional<String> strikeouts,
    @JsonProperty("DOUBLE") Optional<String> doubles,
    @JsonProperty("TRIPLE") Optional<String> triples,
    @JsonProperty("HR") Optional<String> homeruns,
    @JsonProperty("SF") Optional<String> sacFlies,
    @JsonProperty("HBP") Optional<String> hitByPitch,
    @JsonProperty("SB") Optional<String> stolenBases,
    @JsonProperty("CS") Optional<String> caughtStealing,
    @JsonProperty("SEASON") Optional<PlayerSeasonStats> seasonStats,
    @JsonProperty("LOB") Optional<String> leftOnBase,
    @JsonProperty("AVG") Optional<String> battingAverage,
    @JsonProperty("OBP") Optional<String> onBasePercentage,
    @JsonProperty("SLG") Optional<String> slugging,
    @JsonProperty("OPS") Optional<String> onBasePercentagePlusSlugging,
    @JsonProperty("PO") Optional<String> putOuts,
    @JsonProperty("A") Optional<String> assists,
    @JsonProperty("E") Optional<String> errors,
    @JsonProperty("PITCHIP") Optional<String> inningsPitched,
    @JsonProperty("PITCHER") Optional<String> earnedRuns,
    @JsonProperty("PITCHR") Optional<String> pitcherRuns,
    @JsonProperty("PITCHH") Optional<String> pitcherHits,
    @JsonProperty("PITCHBB") Optional<String> pitcherWalks,
    @JsonProperty("PITCHSO") Optional<String> pitcherStrikeouts,
    @JsonProperty("PITCHES") Optional<String> pitches,
    @JsonProperty("STRIKES") Optional<String> strikes,
    @JsonProperty("PITCHOUTS") Optional<String> outs,
    @JsonProperty("ERA") Optional<String> earnedRunsAverage) {}
