package org.sundbybergheat.baseballstreaming.models.wbsc.play;

import com.fasterxml.jackson.annotation.JsonProperty;

public record Player(
    @JsonProperty("name") String fullName,
    @JsonProperty("firstname") String firstName,
    @JsonProperty("lastname") String lastName,
    @JsonProperty("playerid") String playerId,
    @JsonProperty("teamid") String teamId,
    @JsonProperty("teamcode") String teamCode,
    @JsonProperty("image") String imageUrl,
    @JsonProperty("inplay") String inPlay,
    @JsonProperty("reentry") Integer reEntry,
    @JsonProperty("POS") String position,
    @JsonProperty("PA") Integer plateAppearances,
    @JsonProperty("AB") Integer atBats,
    @JsonProperty("R") Integer runs,
    @JsonProperty("H") Integer hits,
    @JsonProperty("RBI") Integer runsbattedIn,
    @JsonProperty("BB") Integer walks,
    @JsonProperty("SO") Integer strikeouts,
    @JsonProperty("DOUBLE") Integer doubles,
    @JsonProperty("TRIPLE") Integer triples,
    @JsonProperty("HR") Integer homeruns,
    @JsonProperty("SF") Integer sacFlies,
    @JsonProperty("HBP") Integer hitByPitch,
    @JsonProperty("SB") Integer stolenBases,
    @JsonProperty("CS") Integer caughtStealing,
    @JsonProperty("SEASON") PlayerSeasonStats seasonStats,
    @JsonProperty("LOB") Integer leftOnBase,
    @JsonProperty("AVG") String battingAverage,
    @JsonProperty("OBP") String onBasePercentage,
    @JsonProperty("SLG") String slugging,
    @JsonProperty("OPS") String onBasePercentagePlusSlugging,
    @JsonProperty("PO") Integer putOuts,
    @JsonProperty("A") Integer assists,
    @JsonProperty("E") Integer errors,
    @JsonProperty("PITCHIP") String inningsPitched,
    @JsonProperty("PITCHER") Integer earnedRuns,
    @JsonProperty("PITCHR") Integer pitcherRuns,
    @JsonProperty("PITCHH") Integer pitcherHits,
    @JsonProperty("PITCHBB") Integer pitcherWalks,
    @JsonProperty("PITCHSO") Integer pitcherStrikeouts,
    @JsonProperty("PITCHES") Integer pitches,
    @JsonProperty("STRIKES") Integer strikes,
    @JsonProperty("PITCHOUTS") Integer outs,
    @JsonProperty("ERA") String earnedRunsAverage) {}
